In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['a', 'b', 'c'])
df

a   b  c
0  8   8  4
1  7   9  5
2  6  10  6
3  5  12  7

In [6]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)
  for l in range(1, L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
  return parameters

In [7]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [8]:
def forwardProp(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b
  return Z

In [9]:
# Forward Prop
def L_layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    A = forwardProp(A_prev, Wl, bl)
  return A,A_prev

In [10]:
X = df[['a', 'b']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['c']].values[0][0]
# Parameter initialization
parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X, parameters)

In [12]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [13]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

<ipython-input-12-f16975403a33>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-12-f16975403a33>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-12-f16975403a33>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [14]:
# epochs implementation
parameters = initialize_parameters([2,2,1])
epochs = 5
for i in range(epochs):
  Loss = []
  for j in range(df.shape[0]):
    X = df[['a', 'b']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['c']].values[j][0]
    # Parameter initialization
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]
    update_parameters(parameters,y,y_hat,A1,X)
    Loss.append((y-y_hat)**2)
  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())
parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [ ]:
#Comparison with keras

In [15]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [17]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.get_weights()

[array([[ 0.94658816, -0.10940492],
        [-1.2180046 ,  0.14552855]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.1183592],
        [-1.2516475]], dtype=float32),
 array([0.], dtype=float32)]

In [27]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]], dtype = np.float32),
               np.array([0.,0.], dtype = np.float32),
               np.array([[0.1],[0.1]], dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [28]:
model.set_weights(new_weights)

In [29]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [30]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [31]:
model.fit(df.iloc[:,0:-1].values,df['c'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 27.9067
Epoch 2/75
4/4 [==============================] - 0s 5ms/step - loss: 27.5811
Epoch 3/75
4/4 [==============================] - 0s 5ms/step - loss: 27.2631
Epoch 4/75
4/4 [==============================] - 0s 5ms/step - loss: 26.9070
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 26.5780
Epoch 6/75
4/4 [==============================] - 0s 5ms/step - loss: 26.2035
Epoch 7/75
4/4 [==============================] - 0s 6ms/step - loss: 25.8599
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 25.4716
Epoch 9/75
4/4 [==============================] - 0s 5ms/step - loss: 25.0702
Epoch 10/75
4/4 [==============================] - 0s 5ms/step - loss: 24.6451
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 24.2575
Epoch 12/75
4/4 [==============================] - 0s 5ms/step - loss: 23.8236
Epoch 13/75
4/4 [==============================] - 0s 5ms/ste

In [32]:
model.get_weights()

[array([[0.37373185, 0.37373185],
        [0.36561266, 0.36561266]], dtype=float32),
 array([0.2723741, 0.2723741], dtype=float32),
 array([[0.37297556],
        [0.37297556]], dtype=float32),
 array([0.20471449], dtype=float32)]